version: '3'
services:
  redis-server:
    image: 'redis'
  counterapp:
    restart: on-failure # possible values - 'no', always, on-failure, unless-stopped
    build: .
    ports:
      - "8080:8080"